name: argos-fairness-evaluator
channels:
  - defaults
  - conda-forge
dependencies:
  - python >=3.9, <3.12
  - pip
  - pandas
  - numpy <3
  - pip:
      - jupyterlab
      - scikit-learn
      - mlflow